enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced Re-eXtended"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"                                                   
excluded-patches = ""                                                 
included-patches = ""                                                 
version = "auto"                                                      
exclusive-patches = false                                             
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
excluded-patches = ""
included-patches = ""
version = "6.41.58"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"
arch = "both"

